source 'https://rubygems.org'
gem 'rails', '4.1.6'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'haml-rails'
gem 'haml'
gem 'carrierwave'
gem 'mime-types', require: 'mime/types'
gem 'rmagick'
gem 'mini_magick'
gem 'activeadmin', github: 'activeadmin'
gem 'devise'
gem 'ckeditor'
gem 'friendly_id', '~> 5.0.0'
